### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AshDarko** [jsteel715/MMM-Brewdog#1]
If i follow your install instructions this causes error on Mirror loading.

Where do you need to put the API key as this is not clear in the documentation?

Can you provide full code of a working config?

Thanks!

**Comment by jsteel715** [comment]
There is no API key required for this module.  If you tell me what error you are getting it will help in troubleshooting

**Comment by AshDarko** [comment]
Well i put this in config:

`{
		module: 'MMM-Brewdog',
		position: "top_left",
		classes: 'Ash',
		config: {
			useHeader: true,
			header: 'Brewdog Beers',
			updateInterval: 60000
		}
	},`

You state there is no install but i ran npm install anyway and this happened:

`npm WARN saveError ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/MagicMirror/modules/package.json'
npm WARN modules No description
npm WARN modules No repository field.
npm WARN modules No README data
npm WARN modules No license field.

audited 1 package in 3.775s
found 0 vulnerabilities
`

And when i run magicmirror i get this and it doesnt run magic mirror:

`Whoops! There was an uncaught exception...
{ Error: Cannot find module 'typed.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Brewdog/node_helper.js:9:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
`

**Comment by AshDarko** [comment]
If i comment out the code in config mirror works again

**Comment by jsteel715** [comment]
This the config I use:
{
			module: "MMM-Brewdog",
			position: "top_left",
			config: {
				useHeader: true,
								
			}
		},

**Comment by jsteel715** [comment]
Can you check your /MagicMirror/node_modules directory and see if there is a directory in there named "typed.js"

**Comment by jsteel715** [comment]
Another thing you can do is just comment out or delete the following line in node_helper.js:  const Typed = require('typed.js');

**Comment by AshDarko** [comment]
Thank you, and sorry for the delay in replying, commenting out that line in node_helper.js worked a treat!

Out of interest, should I have that file?

**Comment by jsteel715** [comment]
You only need it if it is required by any installed modules. In other words, there is no need for the file as long as your system is working. I originally was going to use it for text animation but found another way to do what I wanted. I should have remembered to remove the requirement in the node_helper.js file.
     On Saturday, November 16, 2019, 3:54:23 PM EST, AshDarko <notifications@github.com> wrote:  
 
 
Thank you, and sorry for the delay in replying, commenting out that line in node_helper.js worked a treat!

Out of interest, should I have that file?
